blank_issues_enabled: false
contact_links:
  - name: Questions and Discussions
    url: https://github.com/bradmca/azure-service-bus-and-cosmosdb-web-ui/discussions
    about: Please ask and answer questions here
  - name: Security Issues
    url: https://github.com/bradmca/azure-service-bus-and-cosmosdb-web-ui/security/policy
    about: Please report security vulnerabilities responsibly
